# Generated by Django 2.1.5 on 2019-03-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('page_name', models.CharField(max_length=200)),
                ('who_we_are', models.TextField(help_text='Enter the infoemation about the organisation here.', max_length=1000)),
                ('mission', models.TextField(help_text='Enter the organisations mission here.', max_length=1000)),
                ('vision', models.TextField(help_text='Enter the organisations vision here.', max_length=1000)),
                ('core_values', models.TextField(help_text='Enter the organisations core values here.', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_heading', models.CharField(help_text='Enter heading here', max_length=200)),
                ('message_body', models.CharField(help_text='Enter message body here', max_length=200)),
            ],
        ),
    ]
