# Generated by Django 2.1.5 on 2019-03-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homepage',
            new_name='Home_page',
        ),
    ]
