# Generated by Django 2.1.5 on 2019-03-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20190324_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page',
            name='posted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
