# Generated by Django 2.1.5 on 2019-03-22 16:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memberaccount', '0002_auto_20190322_1900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member_shares',
            new_name='Member_share',
        ),
    ]
